#!/bin/sh
ssh -i JenkinsKey ubuntu@3.110.181.172<<EOF
    cd ~/3DViewer
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v17.6.1
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
